"""Summarise the sensor snapshot that is currently checked out.

Reads data/sensor_readings.csv and params.yaml, writes artifacts/metrics.json.
Do not edit this file: the numbers it writes are what the rest of the team reads.
"""
import csv
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

DATA = ROOT / "data" / "sensor_readings.csv"
PARAMS = ROOT / "params.yaml"
OUT = ROOT / "artifacts" / "metrics.json"


def read_params(path):
    """Flat "key: value" file, one pair per line, # starts a comment."""
    params = {}
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key, value = key.strip(), value.strip()
        if key:
            params[key] = value
    return params


def commit_sha():
    """The SHA of the commit this run came from, if src/provenance.py can say."""
    try:
        from provenance import git_sha
    except Exception:
        return ""
    try:
        return str(git_sha() or "").strip()
    except Exception:
        return ""


def main():
    if not DATA.exists():
        sys.exit("no snapshot at %s" % DATA)

    params = read_params(PARAMS)
    threshold = float(params.get("threshold", "0.5"))
    dataset_digest = hashlib.sha256(DATA.read_bytes()).hexdigest()[:12]

    rows = 0
    alerts = 0
    with DATA.open(newline="") as handle:
        for row in csv.DictReader(handle):
            rows += 1
            if float(row["failure_score"]) >= threshold:
                alerts += 1
    alert_rate = round(alerts / rows, 4) if rows else 0.0

    canonical = ";".join("%s=%s" % (k, params[k]) for k in sorted(params))
    fingerprint = hashlib.sha256(
        (dataset_digest + "|" + canonical).encode("utf-8")
    ).hexdigest()[:16]

    sha = commit_sha()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "alert_rate": alert_rate,
                "alerts": alerts,
                "dataset_digest": dataset_digest,
                "git_sha": sha,
                "params": params,
                "rows": rows,
                "run_fingerprint": fingerprint,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )

    print("rows=%d  alerts=%d  alert_rate=%.4f" % (rows, alerts, alert_rate))
    print("dataset_digest=%s  run_fingerprint=%s" % (dataset_digest, fingerprint))
    if sha:
        print("git_sha=%s" % sha)
    else:
        print("git_sha is empty: src/provenance.py did not report a commit")
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
